spring:
  application:
    name: emotion

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    #password: Likelion1234@
    password:

    #url: jdbc:mysql://localhost:3305/emotion_app?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    #username: root
    #password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # Hibernate DDL 설정은 주석 처리
    # hibernate:
    #   ddl-auto: update


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  show-login-endpoint: true

  spring:
    mail:
      host: smtp.gmail.com            # 1
      port: 587                        # 2
      username: hka97123800@gmail.com               # 3
      password:      # 4
      properties:
        mail:
          smtp:
            auth: true                # 5
            starttls:
              enable: true            # 6
          auth: true

